### ISSUE TITLE
Remove crs_statist_area table from tables.conf

### ISSUE THREAD

**Issue by imincik** [linz/linz-bde-uploader#203]
According

https://app.zenhub.com/workspaces/ds-development-team-5ac39772f2d25356b32ed0f2/issues/linz/bde-processor-deployment/436#issuecomment-493947945

`crs_statist_area` should be commented out from `tables.conf` .

**Comment by strk** [comment]
Removal of crs_statist_area was already done via #39 by removing the table from the default `include_tables` setting. Notice of that is in [CHANGELOG entry for 2.4.0](https://github.com/linz/linz-bde-uploader/blob/debian/2.4.0-3linz_trusty1/CHANGELOG.md#changed) -- The tables.conf entry I'm not sure why I kept it, back then. Maybe as a kind of self-documentation of database-table-to-filename mapping ? Another case of such present-but-unused entry in tables.conf is the one for `crs_street_address` commented to be no-more-unloaded since 2016

**Comment by strk** [comment]
The `crs_street_address` handling was done by @billgeo with 2327157bd3418d597d9210c5e8e1925b0b35fd97

**Comment by strk** [comment]
I'm closing this as already-done
