### ISSUE TITLE
Do we really need -full -full-incremental and -incremental switches ?

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#235]
Can't the code automatically determine what's intended behavior ?

Or I just cannot understand what are those switches really about (they make usage complex)

\cc @palmerj

**Comment by palmerj** [comment]
-full applies a base level_0 dataset, delete existing tables (soon to be truncated instead of dropped via #) before the application of the dataset. This mode is only used on the very first population of a new BDE Processor Database. We likely will never do this again in production.

-incremental is to apply a level_5 dataset over the top of an existing populated dataset, with the datetime of the level_5 dataset needing to be directly after the datetime of the last applied BDE Processor dataset.

-full-incremental is the application of a level_0 (note this) dataset over the top of an existing populated dataset, with the datetime of the level_0 dataset required to be sometime after the datetime of the last applied BDE Processor dataset. This option is used each month for checking if level_5 datasets are somehow missing records in the Landonline incremental change-set process.

To me these options seem like separate unique operations and serve different purposes. What would you propose doing to simplify things?

\cc @imincik

**Comment by strk** [comment]
What I propose to do, to simplify things, is STOP expecting the linz-bde-uploader user (caller) to know what's in the BDE repository. Based on your description, you say that -full and -full-incremental are applied to `level_0` and `-incremental` is applied to `level_5`, but why shoudl the caller know or even care about what's to be uploaded ? It's a bde `uploader` so the user just wants to upload new data, in whichever format it is.

Isn't the purpose always the same ? That is: "please apply any required changes to my DB so it contains the data found in the BDE repository, optionally before the given date"

**Comment by palmerj** [comment]
> but why shoudl the caller know or even care about what's to be uploaded ?

Maybe we are discussing what the default mode of operation should be rather than removing switches? If we do that it's simpler for users.

> It's a bde uploader so the user just wants to upload new data, in whichever format it is.

The 3 options do different things and have different requirements.  On the -incremental case it won't load data if there is a missing level_5 dataset or incomplete next level_5. -full-incremental will just apply if it's newer data.

**Comment by strk** [comment]
What's the use case for preventing load of data when level_5 datasets are missing or incomplete ?

**Comment by palmerj** [comment]
The process will stop in the case of missing or incomplete level5 datasets. Its more if you want to allow the running of full incremental or not. Full of course is about and initial load or reset/rebasing of database from a certain dataset.
